### ISSUE TITLE
Another C++ compiler issue

### ISSUE THREAD

**Issue by Cherry-Crane** [haomateach/cpp#10]
CPSC 1103 R25

Hi, I was following the Udemy instructions to install C++ compiler, and the video showed two command line tool, the xcode-select and the g++. Do I need to download both of them? Are they the same thing?

**Comment by Cherry-Crane** [comment]
I have just installed Xcode-select, but the system doesn't allow me to install g++. Does anyone have similar problem?

**Comment by ZaidIslam** [comment]
They are the same thing. It's just an alternative way to installing the same compiler.

**Comment by haomateach** [comment]
@Cherry-Crane  What's your computer? Mac?

**Comment by Cherry-Crane** [comment]
@haomateach Yes, it's a Mac. 
@ZaidIslam thanks

**Comment by haomateach** [comment]
@Cherry-Crane  Just install one of it. As long as you can see output when you execute

g++ --version
