### ISSUE TITLE
Assignment 7 Due Dates

### ISSUE THREAD

**Issue by Wayd-e** [haomateach/cpp#100]
INFO 1112 (R95)

For assignment and quiz 7 the due dates for are still this coming Monday even though they were moved to week 9, but the peer assessment version of assignment 7 has moved onto assessment early before the due date. Was this an error or would you still like us to do it?

**Comment by Matthew-ELL** [comment]
CPSC 1103 R25
I am having the same problem.

**Comment by haomateach** [comment]
My fault, corrected.
