### ISSUE TITLE
Assignment 6 assessment phase.

### ISSUE THREAD

**Issue by gurnoorsingh-22** [haomateach/cpp#105]
Hello Ma, 
My name is Gurnoor singh i am in your class  
INFO 1112 -R95 . 
As there was no assignment previous week (8) therefore i just misunderstood that the assessment for assignment 6 was also not due for previous week. And thought that it will be for this week 9. But when i checked it i was wrong. 
Due to this misunderstanding i was unable to do the assessment  phase. Can you help me out with this situation.
Thank you, 
Gurnoor singh
100397220

**Comment by William-Aulakh** [comment]
Same happened with me .  is there a way we could correct that sir ?

**Comment by haomateach** [comment]
Hi guys, the score of assignment 6 has been released. Just check moodle more frequently in future, you should find all the upcoming tasks there.
