### ISSUE TITLE
Course 1120 R25 Assessment phase for assignment #7

### ISSUE THREAD

**Issue by kamalbrar1** [haomateach/cpp#106]
I didn't get any file of assignment #7 for assessing yet. But, moodle shows assessment phase has been opened. Is anyone facing the same problem?

**Comment by ZaidIslam** [comment]
Hi, I got the files for assessment, maybe you should check again.

**Comment by gavingro** [comment]
@kamalbrar1 I can confirm that at the time of your original posting, I checked and there were no files.

However, I just checked mine after @ZaidIslam suggested, and there is now files for assessment as there should be.

**Comment by kamalbrar1** [comment]
Thank you guys for informing
