### ISSUE TITLE
Is this week missing from the Moodle?

### ISSUE THREAD

**Issue by gavingro** [haomateach/cpp#107]
_Course and Section Number: CPSC 1103 R25_

Question: 
Is anybody else missing this week (week 11) in the Moodle/Course Website and the Github repo?
I went in today to get started on the week's assignments, but I'm not seeing anything at all below week 10, and I want to make sure it's not a problem on my end.

It'd give me some peace of mind if other students were experiencing the same thing!

**Comment by AdrianPrograms** [comment]
You're not alone with Week 11 stuff missing. Though it's also weird because Week 10 repository isn't showing up on my end. I can only access Week 10 through moodle.

**Comment by gavingro** [comment]
That's good to hear!

I think the week 10 stuff is still there though. Last week, I was confused finding the week 10 materials until I realized the file structure in the GitHub is sorted alphabetically.
So, week 10 is up near the top between week 1-2 and week 3.
Maybe you were making the same error.

That being said, week 11 isn't there yet.

**Comment by AdrianPrograms** [comment]
@gavingro Oh haha! Thanks for pointing it out. I guess all we can do for now is wait.

**Comment by haomateach** [comment]
Sorry guys, it will be updated hopefully tonight!
