### ISSUE TITLE
INFO 1112: Program Structure & Design I (S51) Moodle Content 

### ISSUE THREAD

**Issue by Saahib-Dhanda** [haomateach/cpp#108]
Hey guys, 

I know Professor Ma said he would upload this weeks content by last night, I checked today afternoon and it's not there. I was wondering if this was just me?

**Comment by haomateach** [comment]
It is not updated yet. Sorry for the delay.

**Comment by gurbinder1409** [comment]
when it will be uploaded?
so can we start  with next topic in Udemy?
