### ISSUE TITLE
week 11 missing from the Moodle

### ISSUE THREAD

**Issue by Tao123-debug** [haomateach/cpp#110]
CPSC 1103 (R25) 
Problem: Week 11 is still missing from Moodle, and it's Thursday now.

**Comment by Saahib-Dhanda** [comment]
Yeah I'm facing the same issue.

**Comment by pariharvanshu** [comment]
yeah same here

**Comment by kartikayprashar** [comment]
No homework this week?

**Comment by Tao123-debug** [comment]
Not sure

**Comment by ZaidIslam** [comment]
Yeah, I have the same issue. We should ask for the due date of the quiz and assignment to be extended since we haven't received the homework yet.

**Comment by ZaidIslam** [comment]
According to the course outline, we are supposed to watch S16 smart pointers, but I was waiting for the recommended reading tasks before I watch.

**Comment by Tao123-debug** [comment]
Everyone, It's on Moodle now.
