### ISSUE TITLE
CPSC 1103 Assignment 9 Deadline

### ISSUE THREAD

**Issue by Matthew-ELL** [haomateach/cpp#112]
CPSC 1103 R25

Just to let you know Assignment 9 is set to assessment phase at the moment even though the deadline for submission has not passed yet. This is a problem that has happened before. If you could please change it to submission mode that would be great.

**Comment by Saahib-Dhanda** [comment]
Also Professor, When is the Assignment 9 Deadline?

**Comment by haomateach** [comment]
Thanks. updated.

**Comment by Matthew-ELL** [comment]
The moodle site has not changed. It is still in assessment phase.

**Comment by haomateach** [comment]
Thanks, updated!
