### ISSUE TITLE
What is the difference between "Heap" and "Free Store"?

### ISSUE THREAD

**Issue by gavingro** [haomateach/cpp#114]
_CPSC 1103 R25_

### What is the difference between "Heap" and "Free Store"?

In the Udemy videos and assignments/quizzes, we keep using terms like **the Stack**, **The Heap**, and **The Free Store** to describe different places that the computer holds memory, but I've been a little frustrated that the course doesn't actually want to define them explicitly. Instead, it seems like it talks around them, and assumes you can pick it up?

I do remember the section in the functions about "the Stack", or the function call stack - it seems to me like that's the part of the memory that is planned and accounted for by even the compiler. Things go into that in order, and they get resolved one at a time from the top. This makes sense, especially with the "Stack Unwinding" from this week.

However, in the course our prof has used "the Heap" and "the Free Store" seemingly interchangeably to describe the part of the memory that is dynamically allocated at runtime. Does anyone know the difference between these two areas? 

(I wasn't worried about it too much until I had to make a wild guess on this week's quiz!)

**Comment by kamalbrar1** [comment]
I think heap and free store are same thing. Heap is the memory store during run time and when destructor calls then it become free store. 
Stack: where each function is added by layers.
I am not sure whether it is correct or not.
And the question you are talking about was in the Udemy quiz, if you did it.

**Comment by haomateach** [comment]
http://www.gotw.ca/gotw/009.htm

In this course, you can pretend that they are the same.
