### ISSUE TITLE
Assignment 9 Submission issue

### ISSUE THREAD

**Issue by AdrianPrograms** [haomateach/cpp#115]
Class: INFO 1112: Program Structure & Design I (S51)
ID: 100398503

The submission seems to have skipped the submission phase. Anyone else having this problem?

**Comment by Tao123-debug** [comment]
same here

**Comment by kamalbrar1** [comment]
Same. I am waiting for submission.

**Comment by CalistaHatch** [comment]
Same for me as well, no submission phase only the assessment

**Comment by peninsularcat** [comment]
I'm having the same problem. Also, is this the one that is due on November 22nd? I'm a little confused on the deadlines since there are no dates on the moodle.

**Comment by peninsularcat** [comment]
I am having the same problem.

**Comment by haomateach** [comment]
Updated. Thanks!
