### ISSUE TITLE
assessment 8

### ISSUE THREAD

**Issue by Tao123-debug** [haomateach/cpp#116]
CSPC 1103 (R25)
Problem: One of my peers makes the bug-report into (.cpp) file instead of (.md). Should it affect the marks?

**Comment by gavingro** [comment]
I think not.

**Comment by kamalbrar1** [comment]
Yes, definitely it affects. But you can be lenient after all you have the bug report.

**Comment by Tao123-debug** [comment]
Ok, Thanks
