### ISSUE TITLE
Assignment 9 still in assessment phase

### ISSUE THREAD

**Issue by Matthew-ELL** [haomateach/cpp#117]
CPSC 1103 R25

Just to let you know Assignment 9 is set to assessment phase at the moment even though the deadline for submission has not passed yet. 

I already posted this issue a couple days ago and I was told it was fixed. However Assignment 9 is still set to assessment phase.

**Comment by Matthew-ELL** [comment]
Also the due date for both it and the quiz are set to Dec 1st and Nov 30th respectively.

**Comment by Cherry-Crane** [comment]
He said he has made extensions to A9 deadline to next week in Moodle.

**Comment by Matthew-ELL** [comment]
Ok thank you, I see that now.
The assignment is still in assessment phase so if it could be changed that would be great.

**Comment by haomateach** [comment]
Thanks, updated!
