### ISSUE TITLE
INFO 1112: Program Structure & Design I (S51) Email 

### ISSUE THREAD

**Issue by Saahib-Dhanda** [haomateach/cpp#119]
Hello Professor, 

I emailed you today morning regarding the course content, Please reply at your earliest convivence

Saahib Dhanda 
Student Number: 100320220

**Comment by haomateach** [comment]
Hi Saahib, I did not see that, could you post it here? Thanks.

**Comment by Saahib-Dhanda** [comment]
![image](https://user-images.githubusercontent.com/71110282/100310749-c1d20880-2f62-11eb-9b34-6eeb2ec7b630.png)

**Comment by haomateach** [comment]
Thanks, Saahib. You can check out the announcement sent on 21 September 2020 regarding the late submission policy. I need to make sure that the same policy is consistent for all the students.
