### ISSUE TITLE
Assignment 9: Question 5

### ISSUE THREAD

**Issue by kartikayprashar** [haomateach/cpp#121]
INFO 1112 (R95)

In question 5, do we ask the user to input the 'max' value? And do we store that value in the heap?

``` cpp
  // Ask the user to enter an integer, and store the integer to the variable int

     int integer;
     cout << "Enter an integer: " << endl;
     cin >> integer;
```

**Comment by haomateach** [comment]
You mean Question 7?

**Comment by kartikayprashar** [comment]
@haomateach Sorry, I meant to say question 7.

**Comment by kartikayprashar** [comment]
@haomateach In week 11: Question 5: Fill in the blanks to complete the program.

**Comment by kartikayprashar** [comment]
@haomateach Hi Mr. Ma, should I send you the code?

**Comment by Saahib-Dhanda** [comment]
![image](https://user-images.githubusercontent.com/71110282/100528360-d7c51080-3190-11eb-9cf7-ffec722083b5.png)

I think It would be max, because the variable int is referred to max, but double check with Professor Ma.

**Comment by kartikayprashar** [comment]
@haomateach That came to my mind. Though, let's make sure with Mr. Ma! 😅

**Comment by haomateach** [comment]
@kartikayprashar @Saahib-Dhanda  Saahib is correct, it's a typo. It should be max. I have updated it. Thanks Saahib.
