### ISSUE TITLE
Questions about the Final Exam Format

### ISSUE THREAD

**Issue by gavingro** [haomateach/cpp#124]
_CPSC 1103 R25_

Hi Hao (and class),

Now that the semester is winding down, could you tell us a little bit more about the final exam that we have coming up?

I know that on our syllabus it is worth 10%, which is same as the midterm. 
I can also see from KPU's exam schedule that (for my class/section at least) it is booked for 8:30am on Dec 15.

I'm still curious though: what can we expect the final to be like?
Will it be like the midterm - a short one that's mostly multiple choice?
Will we have to write any programs? How long should we expect to take?
Is it timed for the specific exam time, or is it asynchronous like the midterm and course?

I guess I'm just trying to be prepared for the test. 
I'd appreciate any guidance or extra info you have for this, Hao!

**Comment by haomateach** [comment]
I will email you guys more details about this, but yes, it will be an easy test just like midterm
