### ISSUE TITLE
Assesment phase on assignment 9 not working

### ISSUE THREAD

**Issue by Agupta1011** [haomateach/cpp#126]
Have been repeatedly trying to open the assessment phase but have not been able to open it, Th same issue made me miss the assessment in the previous assignment. Please advise

**Comment by haoma7** [comment]
It has been opened. 
All the assignments have left student at least 4 days for the previous assignment.
But things can happen, and that's why I will remove the lowest score of all assignments in the end, and I have not annouce it yet.

**Comment by haomateach** [comment]
It has been opened.
All the assignments have left student at least 4 days for the previous assignment.
But things can happen, and that's why I will remove the lowest score of all assignments in the end, and I have not annouce it yet.

**Comment by Agupta1011** [comment]
Thankyou sir.
Regards
Anish Gupta

[cid:df7c2989-3358-4cfd-8c7d-9159d4a57d27]

Anish Gupta

IT Manager

www.dcpowersales.com<http://www.dcpowersales.com/>

________________________________
