### ISSUE TITLE
Visual Studio Setup question 

### ISSUE THREAD

**Issue by Tao123-debug** [haomateach/cpp#13]
CPSC 1103 (R25)
 
Problem: I watched the Visual Studio Setup YouTube video that Mr. Hao posted in "Github," and I wonder if we need to set up every time we create a new project? I am going to do the assignment questions in Visual studio, and each question will be a new project. So, is that mean I need to do the setup for each question in the assignment? Thank you.

**Comment by haomateach** [comment]
It is a personal choice, and you can reuse the existing project structure or create a new one.
