### ISSUE TITLE
Assignment 10 Question 7

### ISSUE THREAD

**Issue by Tao123-debug** [haomateach/cpp#130]
CPSC 1103
Problem: Do we need to submit the text file with our codes? If we do, where do we put it in our assignment. Or we just comment in the codes to mention the user to create one text file of their own?

**Comment by Saahib-Dhanda** [comment]
I think either or would work, you could include your own text file in the final submission folder and in our source code you could comment a message saying "// Insert output file between " so and so. Since we're all doing the same question we could use our own text file as well.

**Comment by Saahib-Dhanda** [comment]
I think either or would work here, we could input our own text file or you could include one.
