### ISSUE TITLE
INFO 1112: Program Structure & Design I (S51) Assignment 10 Question 7

### ISSUE THREAD

**Issue by Saahib-Dhanda** [haomateach/cpp#131]
if anyone can clear this misunderstanding, I'd really appreciate it!  

the file we create the two test cases are

 **The program should display the first several lines of the file on the screen, and the number of lines should be equal to the integer entered by the user.**
1) The user enters an integer and that's how many lines should appear; for example if my file has 8 lines but the user inputs 6, the six lines of my file should appear. 

 **If the number of lines the file has is less than the integer entered by the user, then the entire file should be displayed, with a message indicating the entire file has been displayed.**

This is the part of the question where I'm confused at, because if the user enters an integer less than the number of lines the file has, shouldn't it show that specific amount of lines; or is this part of the question  a separate test case where I would create a file with six lines and the user inputs 4 but all six of the file appear.

**Comment by Tao123-debug** [comment]
It means if the number of lines in the file is less than the integer entered by the user. Then, display the entire file.

**Comment by Saahib-Dhanda** [comment]
I'm guessing that is a separate test case then correct?

**Comment by Tao123-debug** [comment]
For example, when the user inputs 8, but there is only 7 line in the file. Then, display all 7 lines with a message indicating the entire file has been displayed.

**Comment by Saahib-Dhanda** [comment]
Yes that is one test case; The other test case is the file has 8 lines but the user enters 4, so only show 4 lines of the file correct?

**Comment by Tao123-debug** [comment]
I think we are not writing test cases since we need the user to input numbers. The user can do it when they test the code.

**Comment by Saahib-Dhanda** [comment]
Yes so the program tests if the user entered more than the amount of lines in the file and displays all lines indicating the entire file has been displayed as well as outputting a specific amount of lines in the file if it's less.

**Comment by kartikayprashar** [comment]
@Saahib-Dhanda @Tao123-debug Guys, are we only working with ONE .txt file for this question?

**Comment by Tao123-debug** [comment]
yes, I think one is enough

**Comment by kartikayprashar** [comment]
@Tao123-debug I mean are we copying one .txt to another? This question is quite confusing!

**Comment by Tao123-debug** [comment]
? You create one text file and use it to test the codes

**Comment by kartikayprashar** [comment]
@Tao123-debug Also, do you know what Mr. Ma means by "display the first several lines of the file on the screen, and the number of lines should be equal to the integer entered by the user"? Don't these two statement contradict one another?

**Comment by Tao123-debug** [comment]
It means when the user inputs an integer (For example, 3), then the codes should only display the first 3 lines of the file.

**Comment by kartikayprashar** [comment]
@Tao123-debug Got it, thanks!

**Comment by kartikayprashar** [comment]
@Tao123-debug Hey one more thing: it says that "If the number of lines the file has is less than the integer entered by the user, then the entire file should be displayed, with a message indicating the entire file has been displayed." Does this mean that the user will enter the value again? The user created the lines, then how can compare if the user entered more or less lines?

**Comment by Saahib-Dhanda** [comment]
No I think it means for example if the file has 6 lines and the user enters 8, The entire file should show including  a message should show indicating the entire file has been displayed.

**Comment by Saahib-Dhanda** [comment]
If the file has 6 lines and the user inputs 4, only 4 lines of the file should show, and no message should be indicating that the whole entire file has been shown, that's my take on it.

**Comment by kartikayprashar** [comment]
@Saahib-Dhanda So the file already exists? I've been thinking that the user created that file.

**Comment by haomateach** [comment]
@Saahib-Dhanda Your understanding is correct.

**Comment by haomateach** [comment]
@kartikayprashar Either works, you can provide testing files to the peer who assesses, or the peer use his/her own if you provide none.

**Comment by Saahib-Dhanda** [comment]
Yes, I think that is what Tao123 was confused about as well, as I guessed either way works !

**Comment by Saahib-Dhanda** [comment]
@haomateach Professor a question, my Program reads the file but if the filename is incorrect It still reads the file. For example in my variable "getfilename" when I prompt the user to enter "getfilename" If I don't type in test.txt which is the txt file I have but I continue with the prompt of entering the integer It still works. I am assuming this is fine?

**Comment by Saahib-Dhanda** [comment]
The file is still able to open.

**Comment by Tao123-debug** [comment]
You can look at Udemy 224, 225, 226. They talked about it

**Comment by haomateach** [comment]
@Saahib-Dhanda You can email me your code.

**Comment by Saahib-Dhanda** [comment]
@haomateach  Just emailed it Professor.
