### ISSUE TITLE
Final Exam for INFO 1112

### ISSUE THREAD

**Issue by Mohamedismail00** [haomateach/cpp#132]
Course and Section Number: INFO 1112 R95
Question: The date of the final exam is written as the 12th of December in the Course Presentation but it's also written in the announcement box as the weekend of Dec 19-20.
When is the exact date for the Final?

**Comment by haomateach** [comment]
Which one do you prefer?

**Comment by Mohamedismail00** [comment]
Any day would be fine with me, I just got confused on which day is it.

**Comment by haomateach** [comment]
Good! Dec 19 - 20.
