### ISSUE TITLE
INFO 1112 R95 Asessment

### ISSUE THREAD

**Issue by RAJWINDER19** [haomateach/cpp#135]
Hello Hao,

greetings of the day,

I am not able to assess any assignment yet but you said that it is opened now. I do not know what exactly happened but there are no assignments for assessing in moodle. i had attached the screenshots please give a look. If you do not able to see screenshots i will send by email because i did not ever attached any screenshot with any issue that is why i am quite unsure about it.

thank you.
![Screenshot (249)](https://user
![Screenshot (250)](https://user-images.githubusercontent.com/71091611/101718714-9ff27e80-3a56-11eb-8e62-8241f133cd77.png)
-images.githubusercontent.com/71091611/101718684-936e2600-3a56-11eb-936b-8fc20313316c.png)

**Comment by haomateach** [comment]
Thanks for the reminder. Corrected!
