### ISSUE TITLE
Cannot mark!!!!!

### ISSUE THREAD

**Issue by kartikayprashar** [haomateach/cpp#136]
INFO 1112 (R95)

Hi, I can't mark the assignments. When I click “Assess,” only the “Please refer to the weekly assignment rubric” displays. Any of you guys are facing the same issue?

**Comment by 91sukhraj** [comment]
The assessment time is over thats why.

**Comment by kartikayprashar** [comment]
91sukhraj But it says the assignment assessment is due today.

**Comment by 91sukhraj** [comment]
It was due 5 minutes past midnight, and past 12 o'clock is considered the next day(Saturday).

**Comment by kartikayprashar** [comment]
@91sukhraj Wasn't the assessment due in six days before? Well, I can't do much now can't I?

**Comment by 91sukhraj** [comment]
Yeah I dont think there is anything you can do now, this assessment was due earlier then usual probably because the semester is going to end soon.

**Comment by haomateach** [comment]
@kartikayprashar extended!

**Comment by kartikayprashar** [comment]
I can access it now. Thank you Mr. Ma!!!!!

**Comment by haomateach** [comment]
Thanks for the reminder. The reason why I set it up as 12.12 is that this is the last class day of the semester, and I forgot that you guys may still think that Sunday night is the deadline.

**Comment by kartikayprashar** [comment]
@haomateach Ah. Got it. Thanks!
