### ISSUE TITLE
Pre-Final Marks

### ISSUE THREAD

**Issue by peterfan727** [haomateach/cpp#140]
Hello Dr. Ma @haomateach 
For the new "Assignment" to submit our own confirmation of the pre-final mark, is it optional?
An issue for that is, I cannot see my previous grades anymore. Everything is hidden.

Screenshot from INFO 1112 S51
![image](https://user-images.githubusercontent.com/70975284/102699264-4fb6b180-41f8-11eb-90a5-fa7d3c3bc1e9.png)

**Comment by haomateach** [comment]
It will be visible once the final is over. 
I think you should be able to check your previous grades in Moodle even if I hide those sections. Isn't there a grade button to click to show all the historical grades?

**Comment by peterfan727** [comment]
Ok, I will check back tomorrow. They're all hidden in the Grades too. 
![image](https://user-images.githubusercontent.com/70975284/102701241-bf816800-4209-11eb-8813-e4b4f5383dd3.png)
