### ISSUE TITLE
Code Lite Mingw not reading

### ISSUE THREAD

**Issue by Agupta1011** [haomateach/cpp#15]
Info 1112 - Program Structure and Design. (R95)

Following the udemy course guide, I followed the correct procedures as per lecture 7. And set the path correctly for the bin file. I received the correct message on the command prompt too. But when I open code Lite the setup wizard doesn't read the Mingw file for some reason?

**Comment by 91sukhraj** [comment]
I had the same problem. Just close/exit Code Lite and open it again. Then it should work.

**Comment by haomateach** [comment]
Follow the guideline here to manully add the compiler

https://wiki.codelite.org/pmwiki.php/Main/AddNewCompiler#toc5

**Comment by Agupta1011** [comment]
> Follow the guideline here to manully add the compiler
> 
> https://wiki.codelite.org/pmwiki.php/Main/AddNewCompiler#toc5

Thankyou Sir

**Comment by Agupta1011** [comment]
> I had the same problem. Just close/exit Code Lite and open it again. Then it should work.

Thankyou Sukhraj
