### ISSUE TITLE
No Compiler Warnings & Linker Errors

### ISSUE THREAD

**Issue by kartikayprashar** [haomateach/cpp#16]
INFO 1112 (R95)

I’m not getting the compiler warnings and linker errors that the person is getting on his console. I typed the same code as he did, but I’m not getting them. I’m using CodeLite.

The code is attached.

<img width="1792" alt="NoCompilerWarnings" src="https://user-images.githubusercontent.com/70995067/93149507-61456600-f6ab-11ea-912d-e707f827eab2.png">

<img width="1792" alt="NoLinkerErrors" src="https://user-images.githubusercontent.com/70995067/93149525-699da100-f6ab-11ea-956a-d8fb3217df15.png">

**Comment by haomateach** [comment]
Pic1: Your code is 100% correct, and that's why you are not getting any warning
Pic2: There is no compiler error here, but it does have link error, since the `x` is not defined here. If you click Build, you will see one error.

**Comment by kartikayprashar** [comment]
Pic1: I have a variable "favorite_number", but it is not used. Should I be getting an error if the variable is not used?

**Comment by haomateach** [comment]
@kartikayprashar You are right, but the warning will only show up the first time you compile it. Afterward, no warning will be displayed. You can verify this.

**Comment by kartikayprashar** [comment]
Oh, ok. Thanks for clarifying.
