### ISSUE TITLE
INFO1112 R95

### ISSUE THREAD

**Issue by RAJWINDER19** [haomateach/cpp#18]
i was trying to create a sub directory naming Q1.cpp in A1 folder but it shows like this.

![Screenshot (173)](https://user-images.githubusercontent.com/71091611/93272647-ce6c0080-f76a-11ea-9bb9-fee0cbdd8caa.png)

**Comment by haomateach** [comment]
It should be Q1.cpp, not Q1.CPP, everything relevant to C++ is case-sensitive. Be careful.
