### ISSUE TITLE
"Public" or "Private" repository?

### ISSUE THREAD

**Issue by kartikayprashar** [haomateach/cpp#21]
INFO 1112 (R25)

For the CppAssignment, do we have to make our repository "Public" or "Private"? You stated Public in the video so you can see the contents but when I click on Assignment 1 on moodle, it says "Make sure you have a private github repository named CppAssignment"?

**Comment by haomateach** [comment]
@kartikayprashar Yes, you are right, and that's why I said in the Assignment Instruction video that I changed my mind, since making it public will make your assignment solution accessible to everyone else. So to sum up, please make it **private**.

**Comment by kartikayprashar** [comment]
Thank you for clarifying!
