### ISSUE TITLE
Assignment Question 14 

### ISSUE THREAD

**Issue by Tao123-debug** [haomateach/cpp#22]
CPSC 1103 (R25) 
Problem: Do anyone know the question 14 "Divide area by force and store the result in the pressure variable." means force/area or area/force?

**Comment by Tao123-debug** [comment]
I didn't very understand that part.

**Comment by haomateach** [comment]
@Tao123-debug 

https://study.com/academy/lesson/force-area-pressure-relationship-applications.html#:~:text=Pressure%20is%20defined%20as%20the,over%20which%20that%20force%20acts.&text=Area%20is%20typically%20measured%20in,name%2C%20Pascals%20(Pa).
