### ISSUE TITLE
Bug Reports

### ISSUE THREAD

**Issue by kartikayprashar** [haomateach/cpp#25]
INFO 1112 (R95)

If we are going to have 3 bug reports, do we have to name our bug reports as following: bug-report-1.md, bug-report-2.md, bug-report-3.md ? Do we specify that a bug report is for which question?

**Comment by peninsularcat** [comment]
Pretty sure we just list the 3 bugs inside bug-report.md

**Comment by kartikayprashar** [comment]
Oh, won't it make it easier to read for the teacher to see if I submitted 3 files?

**Comment by kamalbrar1** [comment]
We need to submit 3 bug reports under one bug-report.md file.

**Comment by kartikayprashar** [comment]
K

**Comment by haoma7** [comment]
@kartikayprashar at least 3 bugs inside 1 single file. It has been covered in the course logistics.

**Comment by kartikayprashar** [comment]
Got it, thanks!

**Comment by haomateach** [comment]
at least 3 bugs inside 1 single file. It has been covered in the course logistics.
