### ISSUE TITLE
Codelite Output Console.

### ISSUE THREAD

**Issue by chevcasey** [haomateach/cpp#26]
When I try to run my programs on Codelite I first click build, then run, then build and execute the way that video 9 from section 2 instructs us to for windows on Udemy.  When I do this I am told that I have 0 errors and 0 warnings, yet the console does not come up on my screen the way it does in video 2-9. What should I try doing to fix this?

**Comment by kamalbrar1** [comment]
Make sure you are not putting your variables in " " .

**Comment by peterfan727** [comment]
Share your codes so we can look at it.

**Comment by haomateach** [comment]
@chevcasey Make sure that when you create a brand new project, change the category to be Console. 
![Capture](https://user-images.githubusercontent.com/65306924/93526031-b2dc3380-f8eb-11ea-9bd9-e034cfb8e654.PNG)

**Comment by chevcasey** [comment]
![Project configuration](https://user-images.githubusercontent.com/70932853/93537643-f3927780-f900-11ea-8ad6-630cfac1858e.png)
Dr. Ma:
I believe my settings match yours. I made sure they are the same and I'm still not getting the console when I run it. I attached a screenshot of the settings I am using incase I am missing something. The only difference I notice is the name of the compiler and the folder, but I doubt that's the issue. In the meantime I am able to use Repl to run and test my codes. However, I would still like to try and get Codelite running too because I would prefer to work on there.
Kamal: 
My variables are not in quotations. The problem is that I do not get the console screen at all, not that the console displays something incorrect.
Peter:
I am pretty sure we aren't supposed to share our codes publicly before the deadline. I do not believe the problem is related to the code. When I build/compile I get 0 errors 0 warnings.

**Comment by haoma7** [comment]
@chevcasey I agree with you this should not be related to the code. Have you set the linker option to -static? If not, check out Section 2 Component 9 Time: 16:11.

**Comment by chevcasey** [comment]
I did forget to do that for a couple of them. I made sure they're all set to static now and I still don't get the console screen. I don't know if it makes a difference or not, but for a split second I see a flash of something that looks like it would be the console screen. I have tried closing all windows and examining the tool bar, but can't find it anywhere.

**Comment by haomateach** [comment]
@chevcasey You are not alone. It seems that it's a common prob. 

https://stackoverflow.com/questions/56526584/codelite-closes-terminal-instantly

There are multiple possible reasons here, and I guess you have to examine each of them on your PC. Let me know if any of those works.

**Comment by chevcasey** [comment]
Thanks! Will do. Good thing Repl will keep us on track if nobody figures it out.

**Comment by haomateach** [comment]
Yeah, no worry. We will figure it out.

**Comment by haomateach** [comment]
@chevcasey Is the problem resolved now?

**Comment by chevcasey** [comment]
Sorry, I decided to prioritize finishing the homework first, and I just submitted it. I can look at that now.

**Comment by haomateach** [comment]
@chevcasey Nice!

**Comment by chevcasey** [comment]
I have tried:
1. using pause("system") and other format variations of those words.
2.leaving both cmd and powershell open
3.closing and reopening codelite
4.making sure the folder name for mingw is not unnecessarily long or including any strange characters.

So far it seems like the simplest and surest way to keep working is to either switch or use multiple IDE's.  So far I have been using codelite and then just copying and pasting my code into repl after, then running it there. That works fine for me and I wouldn't complain about having to continue to do that throughout the semester.

There are multiple suggestions that involve either reinstallation or changing path variables. In my opinion, the most promising thing I haven't tried yet is probably reinstalling the 32 bit version of codelite instead of the 64 bit, and making sure mingw is also 32 bit. My computer is 64 bit, but someone in that thread said he had success switching to 32. However, I am wary about trying the things I haven't yet because I'm worried I might make things worse. The option I mentioned is probably the least risky of all the ones I haven't tried. I can do it, but it would take me awhile. I'll need to refer back to the videos at the same time because I'm still not very familiar with changing paths and things like that. I remember frank said we could do damage if we did things wrong at some points in the video. I'm just not sure if the time and risk are worth it or not when I seem to be able to get by the way things are now. Switching IDE's might be the best solution.

**Comment by haomateach** [comment]
@chevcasey But definitely you should not use REPL across the semester across it's not a full-functioning IDE. 
System setup is common to take several hours, so I suggest you give those potential solutions a shot. Being afraid of making mistakes is not the right attitude towards learning to program...

The reason why switching to 32bit codelite for that guy is that the compiler installed is for 32bit. For your computer, just make sure that both codelite and compiler are for 64 bit. 

Don't be afraid of making things worse. You can also reinstall them to reset them.

**Comment by chevcasey** [comment]
I tried uninstalling codelite and switching to the 32 bit version. That didn't work. I also tried the 64 bit 14.0.0 instead of 14.0.2 version. Someone said that worked for them, but it didn't work for me. I tried these first since they didn't seem too risky. I'll keep trying, but the only things left I don't understand as well.

**Comment by sinarh** [comment]
I had the same problem due to my AVG detection inspecting the console every time it kept popping up which didn't allow the code to execute until it finished inspection.

**Comment by BradonDennis** [comment]
I had the same exact problems running through without being able to see the bottom console at all. I was able to fix it through coming here and working through the link that was shared.

**Comment by chevcasey** [comment]
Yea I'm starting to feel like I'm missing something that you (Brandon) were able to do along with the other people in the link. 

I do have AVG also, so maybe that's a problem. I haven't noticed AVG doing anything to inspect the console, but it could still be doing something while I'm unaware. Sinarh, what did you change with AVG to fix the problem?

**Comment by haomateach** [comment]
@sinarh See the inquiry above 👍
