### ISSUE TITLE
Copy/Pasting the like for the CppAssignment

### ISSUE THREAD

**Issue by kartikayprashar** [haomateach/cpp#28]
INFO 1112 (R95)

When I copy and paste the link in a new private window to see if the link is openable, it says "404 page not found". When I will attach the link, you won't be able to see the files. I have made my repository "private". So what should I do so you may able to see my files?

**Comment by peterfan727** [comment]
I would have the same question. I guess Dr. Ma can only mark with the zipped codes now? Or does Dr. Ma want us to add him as 
a collaborator on our private repositories?

**Comment by brandonb82** [comment]
In the video he says he only wants the zip file now since our repos are should private so only we can see them and to prevent cheating.

**Comment by kartikayprashar** [comment]
I think only zipped files would be awesome. Let's wait and see if Mr. Ma approves it!

**Comment by haomateach** [comment]
Only the zipped file! I guess you guys did not watch the latest Assignment Submission Instruction ...:flushed:
Cheers.
