### ISSUE TITLE
Getters & Setters issue - C++ Tutorial for Beginners

### ISSUE THREAD

**Issue by kartikayprashar** [haomateach/cpp#3]
INFO 1112 (R95)

Problem: I am getting TWO ERRORS for expected member name or ';' after declaration specifiers '} else {' 
AND
 no member named 'getRating' in 'Movie' cout << avengers.getRating();

Here is my code:

``` cpp
#include <iostream>
using namespace std;

class Movie {
  private:
    string rating;
  public:
    string title;
    string director;
    Movie(string aTitle, string aDirector, string aRating) {
      title = aTitle;
      director = aDirector;
      setRating(aRating);
    }

    void setRating(string aRating) {
      if(aRating == "G" || aRating == "PG" || aRating == "PG-13" || aRating == "R" || aRating == "NR")
      rating = aRating;
    } else {
        rating = "NR";
    } 
    
   string getRating() {
     return rating;
   }
};

int main() 
{

  Movie avengers("The Avengers", "Joss Whedon", "PG-13");
  avengers.setRating("Dog");


  cout << avengers.getRating();

return 0;
}
```

**Comment by haomateach** [comment]
@kartikayprashar I don't know where to start.. there are a few errors in the code, but first I want to point out that I have modified your issue, and you can see that  I have used 

``` cpp

```

to enclose your cpp code, which is much nicer than before. You can check out the markdown code to see what I used to do the code highlighting :) Hope that you can check out the markdown cheatsheet to learn how to make markdown text more readable. 

Back to your code, a few errors here:

1. You have an extra { before the **else**
2. You did not define the avengers object correctly. 

I have to say this is a bit too advanced compared to our course progress right now. We are far from there yet!

**Comment by kartikayprashar** [comment]
Hi Mr. Hao,

I tried deleting the '}' before the else but It didn't work. Also, I'm not sure how to define the avengers object correctly.

**Comment by haomateach** [comment]
@kartikayprashar  We will learn about this once we move to Class and Object part of the course. Stay Patient :)

**Comment by kartikayprashar** [comment]
Ok. Thank you Mr. Hao. I was nervous since I have never coded before 😅!

**Comment by haomateach** [comment]
@kartikayprashar Really? Then how come you raised such an advanced question 👍

**Comment by kartikayprashar** [comment]
I watched the C++ Tutorial for Beginners to get familiar with C++!

**Comment by haomateach** [comment]
@kartikayprashar Awesome!

**Comment by kartikayprashar** [comment]
Seems hard but I'll give it my best shot.

**Comment by haomateach** [comment]
@kartikayprashar It certainly seems hard now, but the goal is to gain a high-level understanding of C++. Rest assured that you will find them easy in 2 months.

**Comment by kartikayprashar** [comment]
I hope so, thank you!

**Comment by peterfan727** [comment]
You missed two curly brackets to enclose the body of codes. See correction with ** { ** & ** } ** brackets.

```cpp
void setRating(string aRating) {
      if (aRating == "G" || aRating == "PG" || aRating == "PG-13" || aRating == "R" || aRating == "NR") 
      **{** rating = aRating;
    } else {
        rating = "NR";
    } 
**}**

```

**Comment by kartikayprashar** [comment]
Oh, thank you!
