### ISSUE TITLE
CPSC 1103 R25 - Deleting Repositories

### ISSUE THREAD

**Issue by chevcasey** [haomateach/cpp#30]
I made a mistake making my repository to hand in my homework. Is there a way to delete repositories and files so that it is clear and easy to find which folder is submitted for marking? Also, when I create a folder for A1 inside my CppAssignment repository I do not get the add/upload file option that you still have at that point in the video. I am attaching a screenshot of this so you can see what's happening and hopefully why. The ... beside the go to file option doesn't give me the option to load .cpp files into the A1 folder. I only get that option when I click on the CppAssignment button to get to the start of the master branch. 
![Add files to repository folders](https://user-images.githubusercontent.com/70932853/93539898-e4aec380-f906-11ea-8426-697b0162a8a1.png)

**Comment by haomateach** [comment]
1. Deleting a repo is easy. Go to the Setting and scroll down to the bottom.
2. The reason is that you did not add the README file when creating the repo.

**Comment by chevcasey** [comment]
Thanks

**Comment by chevcasey** [comment]
... For uploading the files I should probably mention that I did add the README file to the repositories I already made. I'll delete the old ones and see if the new repo allows me to upload files in folders.

**Comment by chevcasey** [comment]
Nevermind, I see what you mean now by making the README file. I made one at the beginning but not under A1. I figured it out now. Deleting went smooth too.

**Comment by haomateach** [comment]
@chevcasey OK.
