### ISSUE TITLE
Assignment .cpp File Name Q1/Q2 or Q13/Q14

### ISSUE THREAD

**Issue by peterfan727** [haomateach/cpp#31]
INFO 1112 (S51)

Hello Dr. Ma,

Do you want us to name the .cpp files Q1 for Q13, Q2 for Q14, or just Q13 & Q14?

Also, I noticed when zipping the "A1" folder, and if you open the Zip file, it will have a folder "A1" inside. I just want to make sure this is the way you want it to be. 
![image](https://user-images.githubusercontent.com/70975284/93553689-7da20680-f928-11ea-8ea1-5bacf76e7bb6.png)

Not without the folder inside the zip, right?
![image](https://user-images.githubusercontent.com/70975284/93553760-bb069400-f928-11ea-8bd8-a0ec4c5e08c9.png)

**Comment by DiljodhNahal** [comment]
I'd probably just leave it as Q13/14.

For the folder thing, I doubt it even matters.

**Comment by brandonb82** [comment]
I think it doesn't really matter to much but probably better Q13/14 since then he knows which is which.

**Comment by gavingro** [comment]
I know it's already been said, but I'm going to go with Q13/Q14.
That way, it's explicit to the person who is reviewing my assignment that it is current at a glance.

But yeah, if anybody is taking the time to actually open the files, I'm sure it will be obvious what you are working on.

**Comment by peterfan727** [comment]
Oh, right. I forgot we're getting marked by our peers.

**Comment by haomateach** [comment]
Q13 and Q 14 will be good. 
@peterfan727 Yes, but if you believe the marks you get in the end is not fair, then just let me know and we can review it together.
