### ISSUE TITLE
Quick Clarification: Are we naming our assignments by the week or the assignment number?

### ISSUE THREAD

**Issue by gavingro** [haomateach/cpp#32]
I know this is *such* a nothing question, but I've been watching the videos and I've found conflicting information between different videos about what we should be naming our assignments that we submit.

*Do we label the assignment folders by **week number** or **assignment number**?*

So, this week would look like:
(File Structure by Week Number)

**W2**/
* Q13.cpp
* Q14.cpp
* bug_report_W2.md

(File structure by Assignment number)

**A1**/
* Q13.cpp
* Q14.cpp
* bug_report_A1.md

Again, I know these are pretty much the same, and the actual assignment is very clear. I'm sure most people looking in will easily see all the files and the assignment. I guess I'm just worried about it since we're marking our peers -- I don't want someone hastily giving me a zero just because they don't see the number they're expecting.
The week number and assignment number will be 1 off from each other.

Let me know what you guys have been doing so I can match everyone's expectations! 
In the meantime I'm going to use A1, from the latest "More Assignment Submission Instruction" video.

**Comment by haomateach** [comment]
A1 structure will be good. 

Actually you don't need to worry about this. Since in the end, what you submit is a zip file on Moodle, and github repo is private. Nobody will give you a zero just because of the file name...
