### ISSUE TITLE
HEADS UP: The instructions for calculating pressure in Q14 are inaccurate. 

### ISSUE THREAD

**Issue by gavingro** [haomateach/cpp#33]
Just wanted to let everyone know, it looks like Q14 wants you to calculate pressure as follows:
> Divide area by force and store the result in the pressure variable.

I'm *pretty* sure that pressure is actually force divided by area, and not the other way around.
If you're getting tripped up by this, you're not the only one.

I'm not sure what you folks are doing on your assignments to reflect that, but I've added the initial instructions commented in at the top of my code, as well as some inline comments that explain my thought process. I just went ahead and followed the instructions and wrote a program that uses the inaccurate calculation provided.

**Comment by peterfan727** [comment]
Someone asked this already. Dr. Ma posted a link for the correct formula (F = P/A), so I assume he wants us to follow the correct formula. With that being said, I think some other sections may have submitted the wrong with the wrong formula already.

**Comment by gavingro** [comment]
OH you're absolutely right! I'll close this issue and look harder through the backlog of resolved issues in the future.
 
For everyone reading this, you can see Dr. Ma's original response in issue #22 .
I don't think he's changed the initial question, so you can make your own decisions as to what you'd like to do in your assignment I imagine.
