### ISSUE TITLE
Assignment marking question 

### ISSUE THREAD

**Issue by Tao123-debug** [haomateach/cpp#34]
CPSC 1103
problem: I know that we need to mark 3 people's work, but I am not sure if it's starting next week or this week? I saw the "Assignment 1 Submission (assessment)" in the calendar, but it opens next week. So is that mean we mark this week's assignment next week, and we don't need to do any marking this week?

**Comment by kartikayprashar** [comment]
Same Question!

**Comment by Matthew-ELL** [comment]
I do not believe there is anything to mark yet. The only assignment that has been submitted so far would be assignment 0, which was not worth any marks. However, according to the calendar, assessment for assignment 1 opens on the 22nd which would mean that we would have all of this week (22 - 27) to mark it.
I do not think we will have anything to mark until the 22nd.

**Comment by haomateach** [comment]
Next week. The submission deadline of the Assignment 1 is Sunday midnight, and the assessment starts from next Monday midnight, to allow for late submission.
