### ISSUE TITLE
Week 1 Question 13 & 14.

### ISSUE THREAD

**Issue by Saahib-Dhanda** [haomateach/cpp#35]
Hey Guys,

I hope everyone is doing good and staying safe! 

I just had a question about the assignment, I was confused if Professor Hao wanted us to build and execute a code where the user inputs the following numbers example 20 and 10 for question #13 and then display the product of distance; Or did he want us to just write a program where when you hit run and the program automatically does the math and gives you the product of the distance.

**Comment by ZaidIslam** [comment]
According to the instructions, no code for user input is required. The program should just give the value upon execution of the code.

**Comment by Saahib-Dhanda** [comment]
Thank You.
