### ISSUE TITLE
What are appropriate things to include in bug reports?

### ISSUE THREAD

**Issue by MichaelTann** [haomateach/cpp#37]
Hi all,

I was just wondering what are appropriate things to include for the bug reports? Can they be ANY issue we face during creating the code for the assigned questions? Ex. misspelling code, wrong order of lines, etc?

In addition, what if we have no bugs or not a sufficient amount to meet the "3 bug reports per week" requirement?

Thanks!

**Comment by gavingro** [comment]
I'm hoping that it can be any issue we face - I think you're pretty safe if you can manage to fill out the bug report questions. That being said, I'm going to err on the side of having the bug reports be in errors of my understanding, not just errors of execution. So like, I probably wouldn't include misspelling things, or forgotten semicolons, but I would definitely include "wrong order of lines" if I legitimately thought things could work that way. I think the questions in the report are phrased to encourage us to tackle these kinds of issues.

As for the second question, I'm pretty sure others have asked it and it's been answered. I couldn't find the issue number for you, but if you didn't encounter 3 bugs yourself, you can include bugs that you think others might have encountered. Basically, fake some bugs.

**Comment by MichaelTann** [comment]
Okay thank you.
