### ISSUE TITLE
bug report problems

### ISSUE THREAD

**Issue by skydancer02** [haomateach/cpp#38]
I'm having trouble formatting my bug report every time I turn the file into a .md file the code I've already added gets messed up and kind of merges with the rest of the report.

**Comment by gavingro** [comment]
I'm not sure what exactly you're looking at - a screenshot could help explain what you're dealing with.

With that in mind, markdown makes "code blocks" from certain characters you type. To start a code block, you have to start a line with  "\`\`\`". You can add in your code below it. To end the code block, you need to have a line with another \`\`\`. Then, all the code between the block-ends you declared will be formatted as code. If you include your coding language (for us `cpp`) after the opening "\`\`\`", markdown will specifically highlight the syntax of that coding language for you.

### For Example:
\`\`\`cpp
int main()
{
return 0;
}
\`\`\`

### Becomes
```cpp
int main()
{
return 0;
}
```


In the bug report template Hao provided, he's already included the "```" block headers and enders for us, so we just have to paste in our code between them - just be careful that the block ender is on a line of it's own.

 I believe some of the later blocks (2 and 3) don't include `cpp`, so you can add that in if you'd like.

**Comment by skydancer02** [comment]
okay, that makes sense I think I didn't create any code blocks.
