### ISSUE TITLE
Regarding peer review

### ISSUE THREAD

**Issue by gurbinder1409** [haomateach/cpp#41]
Course INFO 1112 S51
Student#100402388
What about peer review section.

**Comment by edmondwen** [comment]
If I am correct we will be peer evaluating our classmates when the assignments are due. So we should be able to mark them tomorrow? I am guessing?

**Comment by haomateach** [comment]
The Assignment 1 assessment started already.

**Comment by Gurleen989** [comment]
Until which day we can give the assessment on Assignment 1.

**Comment by haomateach** [comment]
@Gurleen989 Deadlines in this course are mostly Sunday midnight. You can also see the deadline in Moodle systems for each assignment submission, assignment assessment and quiz.
