### ISSUE TITLE
Switch statement w/ Int.

### ISSUE THREAD

**Issue by kirkgab** [haomateach/cpp#50]
CPSC 1103: Switch statements
Hello, 
Ive set my switch function with an int. , and set my cases as 1,2,3,4 . My output results in my default statement.

my format is:
``` C++
int selection{};

 court << "statement numbers: " ;
 cin >> selection;

switch (selection) {

 case '1':  cout << "output statement for 1"; break;

default: court << "default statement" << endl;

}
```
... Ive tried switching int into a char, and with cases in alphabet, that seems to work. I have no idea why it doesn't output the chosen case ?

**Comment by peterfan727** [comment]
Errors:

- Typo `court` should be `cout`
- `case '1'` should be `case 1`

**Comment by kirkgab** [comment]
Wait we dont have to use '  ' ? .
btw thanks it worked

**Comment by Saahib-Dhanda** [comment]
Kirk it should be case 1: no quotations for numbers

**Comment by haomateach** [comment]
@kirkgab We certainly don't have to use ' '. For the case statement, the expression should be either a constant or a literal, and it's not bounded to character. 

The `selection` variable is a **int**, so it won't match any char.
