### ISSUE TITLE
Discord channel for students to interact.

### ISSUE THREAD

**Issue by WadeFamer1** [haomateach/cpp#51]
Dr. Ma,
I was hoping that you could put this link in the announcements section for the students to see and join.

Thanks,
Arnav Bhalla
Info 1112
(100409378)

**Comment by haomateach** [comment]
?We already have the discussion forum and we should make the best use of it to get familiar with github.



------------------------------------------------------------------------
Hao Ma, Ph.D., Faculty Member,
Department of Computer Science and Information Technology
School of Business, Kwantlen Polytechnic University
---------------------------------------------------------------------
________________________________
