### ISSUE TITLE
Regarding Quiz Question

### ISSUE THREAD

**Issue by gurbinder1409** [haomateach/cpp#54]
INFO 1112 S15
#100402388
Ques:-  I have question regarding output of this program (in quiz).

What is the output of the following code segment (Please ignore the extra indentation and extra spaces/rows added by Moodle)?

int x = 5;

if (x = 2)

    cout << "This is true!" << endl;

else

    cout << "This is false!" << endl;

    cout << "That's all, folks!" << endl;

**Comment by haomateach** [comment]
Hi @gurbinder1409 , 

- Asking for solutions during the quiz is basically cheating in an exam. 
- Even if you have completed it, it does mean that other students have completed it too. So please don't post this kind of questions too early.
- I don't think I am teaching any BUQU class this semester.

**Comment by haomateach** [comment]
Once the quiz is

**Comment by gurbinder1409** [comment]
I apologize for last issue , actually i have no idea that something serious happen like that.


thanks
