### ISSUE TITLE
Moodle Assessment problem

### ISSUE THREAD

**Issue by Stopren123** [haomateach/cpp#56]
INFO 1112
#100353813

For the Assessment phase, I have no idea how to grade since the page only shows the "access" button? So I thought the Grading evaluation phase is for that. As a result... I have missed that.

Please tell me the detailed process for the next assessment, thx

**Comment by haoma7** [comment]
Could you elaborate on that? The assessment User Interface should be very intuitive. You will have access to the peer's submission, and you have two checkboxes to tick based on the rubric. That is it.

**Comment by haoma7** [comment]
Could you elaborate on that? The assessment User Interface should be very intuitive. You will have access to the peer's submission, and you have two checkboxes to tick based on the rubric. That is it.

**Comment by haomateach** [comment]
Could you elaborate on that? The assessment User Interface should be very intuitive. You will have access to the peer's submission, and you have two checkboxes to tick based on the rubric. That is it.
