### ISSUE TITLE
Cant do assessment on assignment 2

### ISSUE THREAD

**Issue by brandonb82** [haomateach/cpp#57]
Info 1112 (S51)

On moodle for assignment 2 it is showing as submission phase still and not assessment phase, is anyone else having this issue?

**Comment by harkamalsingh1** [comment]
Yes, imfacing that too assesment phase is not activated yet.

**Comment by MichaelTann** [comment]
Yeah, for CPSC 1103 the assignment 2 peer assessment is not in the assessment phase yet.

**Comment by skydancer02** [comment]
same with me

**Comment by edmondwen** [comment]
I think we just have to wait. Since Mr. Ma hasn't set the assessment up yet?

**Comment by haoma7** [comment]
Thanks for the reminder guys, it's open now.

**Comment by haomateach** [comment]
Thanks for the reminder guys, it's open now.

**Comment by peterfan727** [comment]
@haomateach 

Hi, Dr. Ma. I am in S51. My Moodle shows Assessment phase is open since yesterday, but I was not assigned anybody to mark?
![image](https://user-images.githubusercontent.com/70975284/94771295-c5368280-036b-11eb-9db6-99e69d7ef52f.png)

**Comment by haomateach** [comment]
@peterfan727 Thanks a lot for the reminder. It should be working now.

**Comment by skydancer02** [comment]
still don't have anything assigned to assess

**Comment by haomateach** [comment]
@skydancer02 What about now?

**Comment by harkamalsingh1** [comment]
Same with me not working

**Comment by haomateach** [comment]
@harkamalsingh1 It should work now.
