### ISSUE TITLE
Question 20 of assignment 3

### ISSUE THREAD

**Issue by harkamalsingh1** [haomateach/cpp#58]
I have watched the udemy videos twice on c++strings but it only tells to change the data when the iput is already given, what to do when the input is provided by the user??

**Comment by harkamalsingh1** [comment]
i think we have to use functions in order to get a good running code , please clarify me on this topic I'm really suffering while doing the 20th question

**Comment by haoma7** [comment]
Hi, could you let me what you want to achieve? I am not quite sure how to help you here. Some questions may require you to do a bit search out of the udemy course.  In terms of C++ strings, all the operations are the same for user-input strings, and pre-existed string literals.

**Comment by haoma7** [comment]
Hi, could you let me what you want to achieve? I am not quite sure how to help you here. Some questions may require you to do a bit search out of the udemy course. In terms of C++ strings, all the operations are the same for user-input strings, and pre-existed string literals.

**Comment by haomateach** [comment]
Hi, could you let me what you want to achieve? I am not quite sure how to help you here. Some questions may require you to do a bit search out of the udemy course. In terms of C++ strings, all the operations are the same for user-input strings, and pre-existed string literals.

**Comment by harkamalsingh1** [comment]
Hye, professor I want to know that logics about the loops and the c++strings would be enough or not. Because i have checked online there i found the use of functions and pointers we can solve this question without those or not.
Thank you
________________________________

**Comment by haomateach** [comment]
You don't need to learn how to use functions and pointers. But you may need to use some string functions:

http://www.cplusplus.com/reference/string/string/
