### ISSUE TITLE
Been stuck at question #20 for several days now

### ISSUE THREAD

**Issue by AdrianPrograms** [haomateach/cpp#62]
Alright, I have no idea why my methodology does not work.

So here's my thinking:
1.) Get input from user
2.) Identify where the first space is
3.) Get letter from position zero, insert to var 1
4.) Erase letter from position zero
5.) Get letters before the space, insert to var 2
6.) Erase letters before the space
7.) Combine var 2 and var1, add KPU, then a space
Repeat

```

Code removed.  

```

The program just returns incorrectly. Any help would be appreciated.

**Comment by balharmandaher** [comment]
I don't know if this is the root of the problem but I remember a part in the video when doing concatenation you shouldn't add two variable together back to back. So I think your cout << var2 +var1 + KPU might be wrong. But I am not entirely sure. Other than that I really don't know what it could be because this question has me swamped as well. Sorry.

**Comment by AdrianPrograms** [comment]
@balharmandaher 
> I don't know if this is the root of the problem but I remember a part in the video when doing concatenation you shouldn't add two variable together back to back. 

Actually, it's completely fine when adding C++ style strings. However, it's impossible to add C-style strings together multiple times. So something like:

```cpp
var = "This " + " is " + " a sentence.";
cout << var << endl;
```

Will return an error. Thank you for the input anyways, I feel better knowing I'm not the only one completely stumped lol.

**Comment by balharmandaher** [comment]
@AdrianPrograms 
Oh, sorry about that. Thanks, ya hopefully we will be able to figure out this problem.

**Comment by haomateach** [comment]
@AdrianPrograms I have to remove the code here to avoid potential code plagiarism. The code you posted here is too much and too easy to copy.

**Comment by haomateach** [comment]
@AdrianPrograms I have not look further into your code yet, but the first glance at it makes me believe that you may have a misunderstanding of the .find() function. That function only returns the position of the **first** occurrence. So everytime you search " "in the userInput, it always returns the position of the first space.

**Comment by AdrianPrograms** [comment]
@haomateach Thank you for the reply. That's precisely what I'm trying to achieve as the first word is going to be erased anyways to make space for the next word to be processed through.

**Comment by haomateach** [comment]
@AdrianPrograms You probably don't need to erase anything. You may consider another algorithm where you have two position variables i and j where i is pointing at one space, and j is pointing at the next space, and then you can use substr function to manipulate the substring inbetween. In the next loop, and update the i's value with j's value, and then try to find the new value for j.

**Comment by AdrianPrograms** [comment]
@haomateach 

Thank you very much! I did exactly just that and the magic happened; albeit with small tweaks.
