### ISSUE TITLE
Bug Report for Question 20

### ISSUE THREAD

**Issue by kartikayprashar** [haomateach/cpp#63]
INFO 1112 (R95)

For the bug report, I have the bug but don't know how to solve it. Can I still include the bug? The bugs are: Not erasing the letter for EVERY word (only the single beginning word), push_back method not working to include the first letter to the end of word and lastly, I am able to include 'KPU' to the end of the words EXCEPT the very last word. I've tried looking at the website recommended by Mr. Ma: http://www.cplusplus.com/reference/string/string/ However, I'm still unable to correct the bugs.

**Comment by haomateach** [comment]
@kartikayprashar Do you have 3 syntax errors that you have successfully resolved?  If you don't (which is rare), then you can include it.
