### ISSUE TITLE
Week 5 Quiz Closed

### ISSUE THREAD

**Issue by Matthew-ELL** [haomateach/cpp#66]
Hello,

I was on moodle when I noticed that Quiz 4 had closed. I know we have one quiz a week and I thought the quiz that was supposed to be due today was Quiz 3. The corresponding assignment (Assignment 4) is due on Monday October 12. 
I think this is an error of due dates by moodle.
Did anyone else notice this?
Thank you.

**Comment by haomateach** [comment]
​updated. Thanks.
