### ISSUE TITLE
Assignment 4 question 23 

### ISSUE THREAD

**Issue by Tao123-debug** [haomateach/cpp#70]
CPSC 1103 (R25) 
Problem: This is my sample run for my code, I am not sure if this is what should be shown for question 23. Also for the test cases, we are choosing the number "n" right? I didn't include my code, it just a sample run for my code:
![IMG_1658](https://user-images.githubusercontent.com/70913066/95505760-c23b2380-0963-11eb-80b0-5ceacf083a82.jpg)

**Comment by brandonb82** [comment]
I believe that we chose the number for n as that is what I did as well. I looked over the question and it doesn't say about any user input. However it is probably best to see what Hao has to say.
