### ISSUE TITLE
Answers Location

### ISSUE THREAD

**Issue by Gurleen989** [haomateach/cpp#71]
The questions that are explained by professor in the videos under week 2,3,4,,etc. ,can we only find the solutions of questions  by listening to lecture or are the solutions available in written format too .If so ,then where?

**Comment by peterfan727** [comment]
Listen to the lecture. Or post the one you have problem with and we can discuss.

**Comment by haomateach** [comment]
@Gurleen989 The solutions are only in the video. You can search for the solutions in the video.

**Comment by Gurleen989** [comment]
Okay thanks.
