### ISSUE TITLE
Assessing Q19 for Assignment 3

### ISSUE THREAD

**Issue by peterfan727** [haomateach/cpp#72]
Hi @haomateach and peers,

I noticed that some people interpreted Q19 differently than others. One group of us compared "Biology" and "Programming" averages for **each  student** and output which course they spend more time on. Another group of us, **pooled every student's averages for each course** and determined which course they spend more time on.

Should we mark both type of solutions correct?

![image](https://user-images.githubusercontent.com/70975284/95666286-04ec2f80-0b0d-11eb-9478-1f6e42971e0a.png)

![image](https://user-images.githubusercontent.com/70975284/95666352-9065c080-0b0d-11eb-8b95-9faa6eaaee9c.png)

![image](https://user-images.githubusercontent.com/70975284/95666377-b7bc8d80-0b0d-11eb-94f9-6c4aa56f811f.png)

**Comment by ZaidIslam** [comment]
I think the second solution is definitely more accurate in terms of what was asked by the question. Another thing to note is that the first solution has an improper code which makes the output come out as "student 1 on day for programming 1/ biology 1". Instead, the output should be "student1 on programming/biology for day1 ".
