### ISSUE TITLE
Video for assignment 5 not opening

### ISSUE THREAD

**Issue by Agupta1011** [haomateach/cpp#73]
The page keeps displaying media is now loading and click here to refresh, I have tried reloading the page several times logged in and out of moodle too, and tried on different browser as well, cleared the cookies too yet only media is lading comes up.

**Comment by haomateach** [comment]
Please post following the instructions regarding format. I don't know how to answer if you do not provide the right info. Thanks.

**Comment by edmondwen** [comment]
It is available now, It just took awhile to load since Mr.Ma has just uploaded it.

**Comment by haomateach** [comment]
Great

**Comment by Agupta1011** [comment]
Thank you Proffessor
