### ISSUE TITLE
incorrect submission status assignment 4

### ISSUE THREAD

**Issue by skydancer02** [haomateach/cpp#75]
i was checking to see if assignment 4 was in the assesment phase when i noticed that my submission had not updated to include the zip file that i had submitted.

**Comment by haomateach** [comment]
Please post following the instructions and clearly describe the prob. Thanks.

**Comment by skydancer02** [comment]
Course and Section Number: INFO 1112 R95
Question: i was checking the phase of assignment 4 when i noticed my submission didn't have its zip code, even though i did submit it. 
![Annotation 2020-10-13 141705](https://user-images.githubusercontent.com/40615283/95917275-d1084880-0d5e-11eb-8bbd-9136e96cbd27.png)
