### ISSUE TITLE
zip file not showing in submission

### ISSUE THREAD

**Issue by skydancer02** [haomateach/cpp#76]
Course and Section Number: INFO 1112 R95
Question: i was checking the phase of assignment 4 when i noticed my submission didn't have its zip code, even though i did submit it.
![Annotation 2020-10-13 141705](https://user-images.githubusercontent.com/40615283/95918935-84723c80-0d61-11eb-81af-9fb663803e40.png)

**Comment by haomateach** [comment]
You may have forgot to click the submit button at the end. You may consider make that repo public so that others can access it.
