### ISSUE TITLE
Assignment 5 question 15

### ISSUE THREAD

**Issue by Tao123-debug** [haomateach/cpp#78]
CSPC 1103 (R25) 
Problem: For question 15, are we writing a function where the user input numbers? Or we just write the numbers for x and y in the code.

**Comment by gavingro** [comment]
It just says to "demonstrate the function in a complete program", so I believe it is up to you.
You might choose to demonstrate the function with values you provide yourself, or you might get input from the user. I don't believe the actual main() function is the real bulk of that question - it's just a way to show that your function works.

**Comment by kamalbrar1** [comment]
I think user will give the input, otherwise there might be written test your code same as previous assignment
