### ISSUE TITLE
Midterm

### ISSUE THREAD

**Issue by WadeFamer1** [haomateach/cpp#79]
Hello,
I am writing to inquire about the midterm exam. I just wanted to know when would it be and what kind of questions are we expecting?

Thanks,
Arnav Bhalla

**Comment by chevcasey** [comment]
Also, will we be expected to submit pdf documents after taking pictures within a timeframe? I am in CPSC 1103 - R25, and am not sure if Arnav is in the same class. Do we sign on to take the test through moodle when our regular class time would be?

**Comment by 100394454** [comment]
Info1112. S51
Hii,
I too want to know about midterm exam that when and how would it be conducted?
Thank you
Regards,
Khushdeep kaur

**Comment by SarbjotKaurAulakh** [comment]
INFO 1112, R95
Hello Hao,
Could you please confirm us about the midterm exam pattern as well as date and time of the exam so that we will have clear picture for the preparation.
Warm Regards
Sarbjot Kaur

**Comment by haomateach** [comment]
I will post the details of midterm today. Everything will be on Moodle.

**Comment by haomateach** [comment]
Updated!
