### ISSUE TITLE
Regarding course material

### ISSUE THREAD

**Issue by harkamalsingh1** [haomateach/cpp#8]
Course: INFO 1112 , section s51
Student id: 100393340
Is that compulsory to get the textbook or its optional, furthermore the 4 hr video on the youtube and the 1 hrs lectures would be enough or we have to watch any other videos, because it would be very hectic for us to spend around 12 hrs per week on one course because we have other courses as well as we have to go to work too.

**Comment by Saahib-Dhanda** [comment]
Course INFO1112; Section (S51) 
Student ID: 100320220  

Hey Harkamal, as far as I know the only requirement is the Online Learning resource UDEMY course that he has linked. He said 10 Hours a week if I recall but you can cut that down if you play the videos 1.5x. I think the 4 hour video on youtube is recommended not mandatory. 

Below is the info to this link that the Professor has put. --> https://github.com/haomateach/cpp/blob/master/README.md

For most of the weeks, students need to complete weekly:

Udemy video sections (~ 4 hours)
Video uploaded by the instructor (~ 1 hour)
Practice Programming along with video watching (~ 2 hours)
Assignment (~ 2 hours)
Peer Review (~ 15 mins)
Quiz (~ 10 mins)

Hope this helps!

**Comment by harkamalsingh1** [comment]
Yes, i got it but the price of the udemy book is showing 149 dollars thats alot man

**Comment by harkamalsingh1** [comment]
At first it was showing around 20 dollars but now  it starts showing 149 dollars.

**Comment by Saahib-Dhanda** [comment]
Go into Incognito mode it refreshes it and you'll get it for $24.99 I believe

**Comment by DiljodhNahal** [comment]
Incognito mode or open the page without being logged in. It gives you a special offer if you purchase it and signup at the same time I believe.

**Comment by harkamalsingh1** [comment]
So that is a download of textbook or links to videos or what

**Comment by harkamalsingh1** [comment]
So purchasing of udemy is compulsory

**Comment by DiljodhNahal** [comment]
Pretty sure, as the prof said it's going to be our textbook equivalent

**Comment by peterfan727** [comment]
Dr. Ma made a video on how to buy on uAcademy at a discount. It is posted on Moodle. Go watch it. 

The tip is to get around their cookies using incognito/private-browsing mode, and make a new account if they wouldn't give you a discount on the current account you already have.

**Comment by haomateach** [comment]
@harkamalsingh1 Please make sure that you follow the purchase instructions, and don't skip steps.
Also, I don't know where you get the 12 hours per week info?

**Comment by haomateach** [comment]
@harkamalsingh1 We only have the youtube video assigned for week 1.

**Comment by harkamalsingh1** [comment]
Future weeks will then have udemy videos.

**Comment by haomateach** [comment]
@harkamalsingh1 This week too. Please make sure you carefully read the docs I provided. You can find the schedule in the github page. Just click the code and scroll down.
