### ISSUE TITLE
CPSC 1103 - R25 Midterm

### ISSUE THREAD

**Issue by chevcasey** [haomateach/cpp#80]
Hi Hao,

I know there are already other threads messaging you with regards to the midterm, but I decided to start this one also because I didn't notice any associated with my class. Can you please confirm the date and time of the midterm in addition to what we should expect with regards to the format? Will we be able to complete the exam online, or will we be expected to take pictures and submit a .pdf file within a timeframe? How long will the exam be?

Thanks,
Casey Cheveldave

**Comment by haomateach** [comment]
I will post it today.
