### ISSUE TITLE
Using Range-based For-loop "for (auto i : array)" in a function

### ISSUE THREAD

**Issue by peterfan727** [haomateach/cpp#81]
Hello Dr. Ma and class,

There is a bug I have not been able to understand. When we define a function to take in an array as the parameter, why can't I use the for (auto i : array) function? But using normal for-loop when you pass an array into a function (and its size) is ok?

For example,
![image](https://user-images.githubusercontent.com/70975284/96324727-14b9b700-0fd8-11eb-8715-aee5827d128f.png)
would give this error
![image](https://user-images.githubusercontent.com/70975284/96324755-33b84900-0fd8-11eb-8ac8-9c94bca2a1c7.png)

Peter Fan
INFO1112 S51

**Comment by gavingro** [comment]
1. You CAN use range-based-for-loops to iterate through _arrays_.
2. You CANNOT use range-based-for-loops to iterate through _pointers_.

It seems like you are trying to pass in an array as a parameter to the function, then iterate through the array from within the function, which feels like it should work. Unfortunately, **C++ will decay arrays that are passed in as parameters into pointers.** That means that it seems like you are passing in `int array[]` but in fact, the program is changing it into `int *array` under the hood. 

Then, when you try to iterate through `for (auto i : array)`, the program attempts to iterate through the **pointer** passed in called `array`, and then raises an error when it realizes it won't be able to iterate through the pointer.

_I don't know why C++ does this. It seems frustrating and weird._

The easiest solution would be to pass in the array size as well and use a regular for loop to iterate through the array:
```cpp
void print(int array[], int size) {
    for (int j{}; j < size; j++)
        cout << "420blaZEit" << array[j] << endl;
}
```

If you really wanted to use a range based for loop and avoid passing in the size, you could still theoretically do this if you used "pass-by-reference", and passed in a reference to the array. However, if you wanted the program to be able to iterate through, you'd still need to specify the size - in the function definition and declaration:

```cpp
#include <iostream>
using namespace std;

void print(int (&array)[5]) {
  for (auto i : array)
    cout << "peepee"
         << "poopoo" << i << endl;
}

int main() {
  int my_array[]{1, 2, 3, 4, 5};
  print(my_array);
  return 0;
}
```
This means your main function would be clean, but at a huge cost: the `print()` function will only work on arrays of size 5. If you try to run it on an array of a different size, the program won't be able to find the function you're calling, and crash.


From what I found on the internet, I couldn't find a simple way of using a range-based-for-loop on an array in a function, which is a bummer: it seems like it should work. I'd love to hear if anyone found anything different though.

When I was researching this question, I found [this stack-overflow post](https://stackoverflow.com/questions/31824323/range-based-for-loop-in-function-which-passes-an-array-as-value), this [other stack-overflow post](https://stackoverflow.com/questions/7939399/how-does-the-range-based-for-work-for-plain-arrays), and the [documentation](https://en.cppreference.com/w/cpp/language/range-for) to be super helpful.

**Comment by haomateach** [comment]
@peterfan727 Simple answer is that the size info of the array is not passed to the function, so there is no way for the range-based for loop to know when to stop.

**Comment by peterfan727** [comment]
@gavingro @haomateach Thank you! This explains a lot!
