### ISSUE TITLE
Cannot Download zip files from Moodle

### ISSUE THREAD

**Issue by Matthew-ELL** [haomateach/cpp#82]
Hello,

I was going to do the assessments for Week 5 so I went to download the zip files and it gave me an error message for all three. The Moodle site went through maintenance yesterday so I believe that may have affected it because it says that the error could be caused by a server change.
I do not know how I am supposed to mark them.
What should I do?

**Comment by Cherry-Crane** [comment]
I have the same problem.

**Comment by balharmandaher** [comment]
I am having the same problem as well.

**Comment by Saahib-Dhanda** [comment]
Yup, I am getting the same problem as well.

**Comment by BradonDennis** [comment]
Everyone who hasn't grabbed their assessment Zip Files before the maintenance work is going through the same problem as we are. Sadly, I'm not sure there is an easy way to fix this (right away) either than Messaging all your Assessments for their files directly.

If we were able to re-submit in a later time or not get penalized, that would be great for all of us.

**Comment by Saahib-Dhanda** [comment]
I'm hoping we don't get penalized, I mean server changes for KPU is a technical problem on their end, hopefully we get to submit it later.

**Comment by haomateach** [comment]
Assessment Extended. 
@Saahib-Dhanda Of course you won't! 👍

**Comment by Matthew-ELL** [comment]
For anyone wondering, the files are now accessible.
