### ISSUE TITLE
github won't let me edit files

### ISSUE THREAD

**Issue by skydancer02** [haomateach/cpp#83]
Course and Section Number: INFO 1112 R95
Question: I've been trying for the past hour to edit and create files for A5 on GitHub with no success. the website just won't let me commit any changes.

**Comment by haomateach** [comment]
I did not see any Github error. What error messages you see. Please provide more info.

**Comment by skydancer02** [comment]
I did not receive any errors the commit button was just unresponsive.

**Comment by haomateach** [comment]
Try to restart the browser in that case.
