### ISSUE TITLE
Regarding Midterm and Quiz 6

### ISSUE THREAD

**Issue by gurbinder1409** [haomateach/cpp#87]
Course INFO 1213 (R10)

Hi Dr.Hao

This week no quiz, we  just  have to submit assignment2.

**Comment by kartikayprashar** [comment]
There is a quiz (only on assignment 6), a midterm (on everything we've done so far) and assignment 6 (Question 20 and 21).

**Comment by haomateach** [comment]
Please check the email.

**Comment by gurbinder1409** [comment]
Thanks !
