### ISSUE TITLE
getline() function not working

### ISSUE THREAD

**Issue by kartikayprashar** [haomateach/cpp#89]
INFO 1112 (R95)

In this code:

``` cpp
cout << "Please enter your name: " << endl;
getline(cin, user);
cout << endl;
```
I can't enter the name of the person after the first time. Please see the output on the screenshot. Does anyone know what's going on?

<img width="597" alt="Screen Shot 2020-10-21 at 10 04 16 PM" src="https://user-images.githubusercontent.com/70995067/96827199-dcf0ac00-13e9-11eb-992d-29516a2c7e1d.png">

**Comment by kartikayprashar** [comment]
In other words, it doesn't let me enter the name of the persons after the AFTER the first person. If I use cin >> user; then I am all good but I can't put spaces in the name. I am using the 'getline()' function because I want to put spaces.

**Comment by gavingro** [comment]
Hey, I'd love to see a bit more of your code!

As is, it seems like it would work, so I can see why it must be so frustrating.

When we were learning about the buffer and `cin` there was some interesting things. 
Would you be willing to post some more code of the lines before and after the `getline()` function?

**Comment by haomateach** [comment]
@kartikayprashar You can send the code to me via email.

**Comment by kartikayprashar** [comment]
@haomateach Sure, thank you!

**Comment by kartikayprashar** [comment]
@haomateach Hi Mr. Ma, the 'gets()' function is also not working.

**Comment by haomateach** [comment]
@kartikayprashar I reviewed your code, and the prob does not reside in whether `cin>>` or `getline` or `gets`, it resides in the lack of "this" pointer. Check out Section 151. So basically you need to use the `this` pointer to explicitly tell the compiler that you are refer to the "user" of that object. Otherwise, random things happen. C++ is not that smart, right :) 

Simply speak, replace your ```user``` in ```setValue()``` function as ```this->user```

Let me know once you complete this, and then I want to tell you more about further improvement.

**Comment by kartikayprashar** [comment]
@haomateach Hi Mr. Ma, I tried using these using the 'this' pointer. However, the same problem remains!

``` cpp
cin >> this->user; // Works well without spaces!
getline(cin, this-> user); // Works bad with or without spaces!
```

**Comment by haomateach** [comment]
@kartikayprashar I see. I was using `cin>>` all the time so I did not run into this problem.

The bug here is not an easy one. Please refer to

https://stackoverflow.com/questions/21567291/why-does-stdgetline-skip-input-after-a-formatted-extraction

you need to use `cin.ignore()` to flush the line

**Comment by kartikayprashar** [comment]
@haomateach Thank you Mr. Ma! This definitely works with our without spaces. But just one little issue (ONLY ON THE FIRST INPUT): the first letter of the word is cut off. Suppose I write 'Frank' (only on the first try, rest are fine). It prints out 'rank'.

**Comment by haomateach** [comment]
what are you using now?

**Comment by kartikayprashar** [comment]
This method:
``` cpp
getline(cin.ignore(), user);
```

**Comment by haomateach** [comment]
Then just use `cin`, mixing both is making things way too complicated.

**Comment by kartikayprashar** [comment]
@haomateach 
Sure Mr. Ma,
And may I tell the user to enter the person's name without any spaces? That will make things easier!

**Comment by haomateach** [comment]
The question is harder than I expect. OK, you can keep the getline in order to accept input with space. Now put
```cpp
cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n')

```
at the end of setValues() function before the closing curly brace. It would work. Let me know if it works for you.

**Comment by kartikayprashar** [comment]
@haomateach Yes Mr. Ma, this works 100% of the time. Everything good! Thank you for the help!!!!!

**Comment by haomateach** [comment]
@kartikayprashar Then let's talk about further improvement.

What you did is not following the common practice.

In common practice, the setValue function should accept arguments, since it's a setter function. The cin and getline function are not put inside the method implementation. Instead, they are in the main function.

**Comment by kartikayprashar** [comment]
@haomateach Hi Mr. Ma
If I provide the arguments:
``` cpp
void setValues(string usr, double rate, double hours)
Don't I have to provide the values manually rather than inputting values from the user using cin?
```
Like that?:
``` cpp
PayRoll nm;
nm.setValues("Kartikay", 10, 40);
```

**Comment by haomateach** [comment]
You can still ask for user input in the main function, right? and then pass that information to the setValues. The two features are not mutual-exclusive.

**Comment by kartikayprashar** [comment]
@haomateach Hi Mr. Ma, this way:
``` cpp
    for (int i {0}; i < 2; i++) { // Setting Values
        person[i].setValues(usr, rate, hours);
    }
```
I have put the cin in the main function.
But the person, hourly wage, hours, and total wage is coming up the same for each and every person even thought I input different names, wage, and hours. May I use the other way?

**Comment by haomateach** [comment]
The code obviously will use the same usr, rate and hours value for every iteration. So you need to put the cin inside the for loop body.

**Comment by kartikayprashar** [comment]
@haomateach Hi. Mr. Ma, I got the code to work but I'm still wondering as to why do we put this inside the 'for loop' where I'm asking the user for 'cin'. Why can't we have it outside the for loop separate from the 'for loop' where the 'cin' exists?:
``` cpp
person[i].setValues(usr, rate, hours);
```

**Comment by kartikayprashar** [comment]
@haomateach I think I got it Mr. Ma. Thank you!
