### ISSUE TITLE
C++ compiler question 

### ISSUE THREAD

**Issue by Tao123-debug** [haomateach/cpp#9]
CSPC 1103 (R25) 
Problem: I am watching the Learn C++ in 4 hours video, and I tried to set up a C++ compiler using the video. However, I found out that my computer doesn't have a thing called "Terminal" to install a C++ compiler like what the video shows. So, what should I do now? I had the Visual Studio 2017 installed.

**Comment by pariharvanshu** [comment]
Hey!
So If you can get the Udemy course they have explained in a better way how to install the compiler. But you are good to go even if you have Visual Studio 2017.
