### ISSUE TITLE
Assignment #5 Peer Assessment Locked?

### ISSUE THREAD

**Issue by peterfan727** [haomateach/cpp#90]
@haomateach 

Dear Dr. Ma,
I am in INFO1112 S51.
Moodle says it should have opened, but I don't see anything for assessment.
![image](https://user-images.githubusercontent.com/70975284/96930402-7c588200-1470-11eb-85ca-e8dfcad50dab.png)

**Comment by haomateach** [comment]
It should be opened now, right? Thanks for letting me know!

**Comment by peterfan727** [comment]
Confirmed fixed.
