### ISSUE TITLE
INFO 1112: Program Structure & Design I (S51) Debugger customization 

### ISSUE THREAD

**Issue by Saahib-Dhanda** [haomateach/cpp#94]
Hey guys ! I was just wondering if anyone could advise me on my debugger customization. as of now it shows  the Name & Value but it does not show the type. Anyone know how I can add that? Thanks ! 

![picture](https://user-images.githubusercontent.com/71110282/97121131-2a666500-16d9-11eb-9718-0df8d9ade641.PNG)

**Comment by kartikayprashar** [comment]
Click on the arrows (>) below the 'Name' section. See what comes up!

**Comment by kartikayprashar** [comment]
@Saahib-Dhanda Click on the arrows (>) below the 'Name' section. See what comes up!
