### ISSUE TITLE
github commit and add file buttons unresponsive

### ISSUE THREAD

**Issue by skydancer02** [haomateach/cpp#97]
I have tried refreshing and restarting the browser window with no success of fixing the problem.

**Comment by haomateach** [comment]
Please take a screenshot. I need to see the detail.

**Comment by skydancer02** [comment]
this is it.

**Comment by skydancer02** [comment]
nevermind it wont let me post images either

**Comment by haomateach** [comment]
You can email me.

**Comment by skydancer02** [comment]
new discovery I can ZIP any existing files either

**Comment by skydancer02** [comment]
*can't

**Comment by skydancer02** [comment]
if it wasn't the fact that I can post about the issue I would assume that the problem is our terrible wifi

**Comment by haomateach** [comment]
You know that you can edit the posted issue, right...? You don't have to post so many new posts.

**Comment by skydancer02** [comment]
adding stuff to the message didn't work anything still can't commit the changes. I also don't see how that's supposed to help my inability to make new files.

**Comment by haomateach** [comment]
Again, please email me the screenshots with the message added.
