### ISSUE TITLE
Assignment 5 assessment

### ISSUE THREAD

**Issue by Gurleen989** [haomateach/cpp#98]
In my assignment 5 assessment . I got 24 out of 80  and he/she marked the option No source code is provided ............  
and wrote in feedback that he / she was unable to access my code as it was not in .cpp format .So , I don't know whether it was the error in my assignment or what that  he was unable to access my code and marked the first option. So , can anyone please explain where was the error as I do not want to loose marks like that next time because according to me I provided the complete solution of both the questions in my assignment .

**Comment by haoma7** [comment]
First, please provide your info, including your name, course name, section no. via email to me so that I can investigate. This kind of question usually won't receive answers here since not everyone has enough info to help you.

**Comment by haomateach** [comment]
First, please provide your info, including your name, course name, section no. via email to me so that I can investigate. This kind of question usually won't receive answers here since not everyone has enough info to help you.
